#!/usr/bin/env bash

# Define the octocat ASCII art
octocat="    /\\___/\\
   ( =^.^= )
    >  \"  <"

# Define the message to display
message="....\"Have you meowed today?\"..."

# Print the octocat and the message
echo "$octocat"
echo "$message"
